export default function Home(){return <main>
  <nav><a className="brand" href="/">จด<span>ใจ</span><small>JOD-JAI</small></a><a className="nav-link" href="https://line.me/R/ti/p/@332nhscs">เปิดใน LINE ↗</a></nav>
  <section className="hero"><div className="intro"><div className="eyebrow"><span/> สมุดรายจ่าย ในแชตของคุณ</div><h1>ส่งสลิปแล้ว<br/>ให้เราช่วย<span>จดใจ</span></h1><p>เก็บรายจ่ายเล็ก ๆ ในทุกวันให้เป็นเรื่องง่าย<br/>อ่านข้อมูลจากสลิป เติมเรื่องราว แล้วค่อยยืนยัน</p><a className="cta" href="https://line.me/R/ti/p/@332nhscs">เริ่มจดผ่าน LINE <span>↗</span></a><div className="supported">รองรับ เป๋าตัง · MAKE · Bangkok Bank · SCB</div></div>
  <div className="hero-qr"><img src="/line-oa-qr.svg" alt="LINE OA QR Code" width="160" height="160"/><p>สแกนเพื่อเพิ่มเพื่อน LINE OA</p><a className="qr-link" href="https://line.me/R/ti/p/@332nhscs">หรือกดที่นี่เพื่อเปิดใน LINE</a></div>
  <div className="chat"><div className="chat-header"><div className="avatar">จ</div><div><strong>Jod-Jai</strong><small>ผู้ช่วยจดรายจ่ายของคุณ</small></div><span className="dots">•••</span></div><div className="chat-body"><div className="day">ตัวอย่างการใช้งาน</div><div className="slip"><span className="check">✓</span><strong>ชำระเงินสำเร็จ</strong><b>96.00 <small>บาท</small></b><span>ร้านตัวอย่าง</span><div className="slip-lines"/></div><div className="bubble">อ่านสลิปแล้ว 96 บาท<br/>รายการนี้เป็นค่าอะไรครับ?</div><div className="answer">ค่าอาหารเย็น</div><div className="confirmation"><div className="overline">ตรวจสอบก่อนบันทึก</div><h2>ค่าอาหารเย็น</h2><div className="amount">96.00 <span>บาท</span></div><div className="detail"><span>หมวดหมู่</span><b>อาหาร</b></div><div className="draft">รายการร่าง · ยังไม่นับในยอดรายจ่าย</div><div className="preview-button">✓ ยืนยันและบันทึก</div><div className="edit">แก้ไข <span>·</span> ยกเลิก</div></div></div></div></section>
  <section className="steps"><article><span>01</span><h3>ส่งสลิป</h3><p>ส่งรูปเข้าแชตส่วนตัวกับ OA<br/>อ่านยอด วันเวลา ผู้รับ และหมายเหตุ</p></article><article><span>02</span><h3>เติมรายละเอียด</h3><p>มีหมายเหตุอยู่แล้วก็ดึงมาใช้<br/>ถามเพิ่มเฉพาะข้อมูลที่ยังขาด</p></article><article><span>03</span><h3>ตรวจแล้วค่อยบันทึก</h3><p>คุณเป็นคนยืนยันทุกครั้ง<br/>รายการร่างยังไม่รวมในยอดรายจ่าย</p></article></section>
  <section className="faq"><h2>คำถามที่พบบ่อย</h2><details><summary>อ่านสลิปไม่ได้/ไม่ครบ ต้องทำไง?</summary><p>ส่งภาพสลิปเต็มที่ชัดเจน รองรับ เป๋าตัง MAKE Bangkok Bank SCB หากข้อมูลสำคัญขาด ให้พิมพ์ต่อในบรรทัดเดียว คั่นด้วย comma เช่น 96.00, 2026-09-26 19:30, ร้านตัวอย่าง</p></details><details><summary>ข้อมูลส่วนตัวปลอดภัยไหม?</summary><p>รูปสลิปอ่านในหน่วยความจำแล้วทิ้งทันที ไม่เก็บไฟล์ ไม่ส่งให้ AI ภายนอก ข้อมูลแยกตาม LINE User ID เฉพาะคุณเข้าถึงได้</p></details><details><summary>เพิ่มเพื่อนใช้ร่วมได้ไหม?</summary><p>ได้ เจ้าของพิมพ์ “เชิญเพื่อน” ได้รหัส ให้เพื่อนแอด OA พิมพ์ “เข้าร่วม {'<'}รหัส{'>'}” ข้อมูลแต่ละคนแยกกัน</p></details><details><summary>ลบรายการผิด แก้ยังไง?</summary><p>พิมพ์ “แก้รายการล่าสุด” หรือ “รายการค้าง” เลือกแก้ได้ ยกเลิก/ลบก็ได้</p></details><details><summary>ส่งออกข้อมูลเป็น CSV ได้ไหม?</summary><p>ได้ พิมพ์ “ส่งออกข้อมูล” ได้ลิงก์ดาวน์โหลด CSV หมดอายุ 10 นาที</p></details><details><summary>รูปสลิปมีข้อจำกัดขนาดไหม?</summary><p>รูปต้องไม่เกิน 12 MB แนะนำให้ถ่ายภาพชัดเจน ส่องแสงดี หากใหญ่เกินไปให้ลดขนาดก่อนส่ง</p></details></section>
  <footer><span>Jod-Jai — จดรายจ่าย ให้เบาใจ</span><span>สำหรับการใช้งานส่วนตัวผ่าน LINE</span></footer>
  </main>;}
